### PR TITLE
Migrate master branch in release v0.44.3

### PR DESCRIPTION
**Pull request by cgkournelos-rf**
## Description
Update the master branch version from v0.41.0 to v0.44.3.

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?
Tested locally by following the tutorial steps in the [Datapipeline doc](https://docs.kyve.network/data_engineers/accessing_data/elt_pipeline/overview).

## Changelog
Follows the Airbyte release changelog

### CODE REVIEW

**Comment by eferm** [comment]
Sheesh what a diff. @cgkournelos-rf these are only changes from Airbyte, and no changes to the KYVE connector?

**Comment by cgkournelos** [comment]
Exactly @eferm.
The goal is to keep the fork close to the upstream's stable versions until the final integration of the KYVE connector.

**Comment by cgkournelos-rf** [comment]
> Sheesh what a diff. @cgkournelos-rf these are only changes from Airbyte, and no changes to the KYVE connector?

Yes @eferm. 
The goal is to keep close to the stable releases of airbyte to detect any potential conflicts with the KYVE connector.
For this version, everything seems to work fine.

**Review by eferm — APPROVED** [review]
let's merge it

**Pull request merged**
